// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// import 'firebase_options.dart';
// ...
// await Firebase.initializeApp(
//   options: DefaultFirebaseOptions.currentPlatform,
// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD19qX0KAlnwG1kKxLbOLsW0EWd3rioRzU',
    appId: '1:603014474661:web:6a96a7c92c870be06c164c',
    messagingSenderId: '603014474661',
    projectId: 'pdf-app-d3404',
    authDomain: 'pdf-app-d3404.firebaseapp.com',
    storageBucket: 'pdf-app-d3404.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9WOscxk7-X0u7ccEAjYMgSR6pz0syMpA',
    appId: '1:603014474661:android:1e7860fda42f45026c164c',
    messagingSenderId: '603014474661',
    projectId: 'pdf-app-d3404',
    storageBucket: 'pdf-app-d3404.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAduFSGPinOpMWHstzW8Xba1ZaPx3blsY',
    appId: '1:603014474661:ios:260d1e14063877f46c164c',
    messagingSenderId: '603014474661',
    projectId: 'pdf-app-d3404',
    storageBucket: 'pdf-app-d3404.appspot.com',
    iosBundleId: 'com.example.pdfApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAduFSGPinOpMWHstzW8Xba1ZaPx3blsY',
    appId: '1:603014474661:ios:695caae44be865f06c164c',
    messagingSenderId: '603014474661',
    projectId: 'pdf-app-d3404',
    storageBucket: 'pdf-app-d3404.appspot.com',
    iosBundleId: 'com.example.pdfApp.RunnerTests',
  );
}
